spring:
  config:
    activate:
      on-profile: sit

  datasource:
    url: jdbc:postgresql://localhost:5432/foodies?cloudSqlInstance=stellar-463207:us-central1:stellar-1&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
    username: foodies_order
    password: u123456
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: foodies_order
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  JWT_SECRET: sD9fK!eR#8vP@wX2zL0qT&jM$1nG^cY7
  
