runtime: java17
service: product-service
entrypoint: "java -Dspring.profiles.active=sit -jar target/product-0.0.1-SNAPSHOT.jar"

beta_settings:
  cloud_sql_instances: stellar-463207:us-central1:stellar-1