spring:
  config:
    activate:
      on-profile: sit

  datasource:
    url: jdbc:postgresql://localhost:5432/foodies?cloudSqlInstance=stellar-463207:us-central1:stellar-1&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
    username: foodies_user
    password: u123456
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: foodies_users
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  JWT_SECRET: "sD9fK!eR#8vP@wX2zL0qT&jM$1nG^cY7"
google:
  client-id: 867187817891-ga6228nh62eu8217fiec5hf5qknpi1f8.apps.googleusercontent.com